/**
 * Pool of realistic Indian full names for seeded demo students (roll SH-*).
 * Index is chosen deterministically from roll number so re-seeds stay stable.
 */
const INDIAN_STUDENT_NAMES = [
  'Arjun Sharma',
  'Priya Singh',
  'Rohan Verma',
  'Ananya Iyer',
  'Vikram Patel',
  'Neha Kapoor',
  'Aditya Reddy',
  'Kavya Menon',
  'Siddharth Joshi',
  'Divya Nair',
  'Manish Agarwal',
  'Sneha Deshmukh',
  'Rahul Bhatt',
  'Pooja Malhotra',
  'Karan Mehta',
  'Meera Krishnan',
  'Nitin Chauhan',
  'Lakshmi Rao',
  'Dev Bakshi',
  'Ishita Sen',
  'Ravi Sundaram',
  'Tanvi Pillai',
  'Harsh Khanna',
  'Shruti Bansal',
  'Akash Dutta',
  'Simran Gill',
  'Varun Tiwari',
  'Aishwarya Chopra',
  'Yash Kulkarni',
  'Riya Shah',
  'Pranav Nambiar',
  'Kiran Hegde',
  'Omkar Das',
  'Swati Mishra',
  'Aniket Pandey',
  'Fatima Khan',
  'Kabir Ansari',
  'Zara Qureshi',
  'Ayaan Sheikh',
  'Diya Thomas',
  'Nithya Raman',
  'Deepak Modi',
  'Jyoti Saxena',
  'Gautam Sinha',
  'Pallavi Bose',
  'Rajesh Krishnamurthy',
  'Sunita Varma',
  'Mohit Saxena',
  'Geeta Agarwal',
  'Chetan Pandey',
  'Nisha Rao',
  'Vinay Redkar',
  'Aparna Shastri',
  'Bikash Patra',
  'Chandni Oswal',
  'Esha Bhattacharya',
  'Farhan Malik',
  'Gaurav Sethi',
  'Harini Subramanian',
  'Ishaan Pawar',
  'Juhi Chauhan',
  'Kunal Thakur',
  'Leela Srinivasan',
  'Mihir Banerjee',
  'Nandini Basu',
  'Ojas Trivedi',
  'Parul Mishra',
  'Rachit Agarwal',
  'Saanvi Desai',
  'Tarun Bhatia',
  'Urvashi Kulkarni',
  'Vedant Ghosh',
  'Yamini Krishnan',
  'Aarav Saxena',
  'Bhavya Joshi',
  'Chirag Malhotra',
  'Dhruv Nair',
  'Ekta Verma',
  'Firoz Khan',
  'Gayatri Iyer',
  'Himanshu Pandey',
  'Inaya Sheikh',
  'Jayesh Patel',
  'Khushi Reddy',
  'Lavanya Rao',
  'Madhav Srinivas',
  'Navya Menon',
  'Ovi Chatterjee',
  'Prisha Kapoor',
  'Rehan Qureshi',
  'Sara Thomas',
  'Tanya George',
  'Uday Krishnan',
  'Vanya Subramanian',
  'Waseem Akhtar',
  'Zainab Malik',
];

function nameForShRoll(roll) {
  const m = String(roll).match(/^SH-(\d+)-([A-Z])-(\d+)$/i);
  if (!m) return 'Student';
  const classNum = parseInt(m[1], 10) || 0;
  const secIdx = m[2].toUpperCase().charCodeAt(0) - 65;
  const num = parseInt(m[3], 10) || 0;
  const idx = Math.abs(classNum * 47 + secIdx * 19 + num * 7) % INDIAN_STUDENT_NAMES.length;
  return INDIAN_STUDENT_NAMES[idx];
}

module.exports = { INDIAN_STUDENT_NAMES, nameForShRoll };
